import { RISK_CONFIG } from "@/features/trading-agent/constants/risk.constants";
import { Position, TradingDecision, PortfolioSnapshot, TickerData } from "@/features/trading-agent/types";

export interface RiskValidationResult {
  isAllowed: boolean;
  reason?: string;
  adjustedDecision?: TradingDecision;
}

/**
 * RiskManager Service
 * Responsible for validating trading decisions against predefined safety constraints.
 */
export class RiskManager {
  /**
   * Validates a trading decision against portfolio constraints and risk limits.
   * @param decision The decision generated by the LLM.
   * @param portfolio The current state of the portfolio.
   * @param tickerData The current market data for the symbol.
   * @returns A RiskValidationResult indicating if the trade is allowed and why.
   */
  public validateDecision(
    decision: TradingDecision,
    portfolio: PortfolioSnapshot,
    tickerData?: TickerData
  ): RiskValidationResult {
    if (!decision || decision.action === "hold") {
      return { isAllowed: true };
    }

    if (decision.size === undefined || decision.size <= 0) {
      return {
        isAllowed: false,
        reason: `Invalid trade size (${decision.size}) for active action (${decision.action})`,
      };
    }

    // 1. Check Conviction Threshold
    if (decision.strength < RISK_CONFIG.MIN_CONVICTION_THRESHOLD) {
      return {
        isAllowed: false,
        reason: `Conviction strength (${decision.strength.toFixed(2)}) is below threshold (${RISK_CONFIG.MIN_CONVICTION_THRESHOLD})`,
      };
    }

    // 2. Check Concurrent Positions
    const openPositions = portfolio.positions.filter(p => p.side === "long" || p.side === "short");
    if (openPositions.length >= RISK_CONFIG.MAX_CONCURRENT_POSITIONS) {
      return {
        isAllowed: false,
        reason: `Maximum concurrent positions (${RISK_CONFIG.MAX_CONCURRENT_POSITIONS}) reached`,
      };
    }

    // 3. Check Minimum Trade Value
    if (tickerData && tickerData.lastPrice > 0) {
      const estimatedValue = decision.size * tickerData.lastPrice;
      if (estimatedValue < RISK_CONFIG.MIN_TRADE_VALUE) {
        return {
          isAllowed: false,
          reason: `Trade value ($${estimatedValue.toFixed(2)}) is below minimum threshold ($${RISK_CONFIG.MIN_TRADE_VALUE})`,
        };
      }
    }

    // 4. Check Position Size Limit
    if (tickerData && tickerData.lastPrice > 0) {
      const positionValue = decision.size * tickerData.lastPrice;
      const maxAllowedValue = portfolio.equity * RISK_CONFIG.MAX_POSITION_SIZE_PCT;

      if (positionValue > maxAllowedValue) {
        // Adjust the decision to fit within limits
        const adjustedSize = maxAllowedValue / tickerData.lastPrice;
        
        // Update the decision with the adjusted size
        const adjustedDecision = {
          ...decision,
          size: adjustedSize,
          reason: `Adjusted: Original size exceeded max position limit (${(RISK_CONFIG.MAX_POSITION_SIZE_PCT * 100).toFixed(0)}% of equity)`,
        };

        return {
          isAllowed: true,
          reason: `Adjusted size from ${decision.size.toFixed(4)} to ${adjustedSize.toFixed(4)}`,
          adjustedDecision,
        };
      }
    }

    return { isAllowed: true };
  }
}

export const riskManager = new RiskManager();
